const prefix = "[wozjac.ui5]";

define({
    "UI5_TOOLS_MENU": "UI5 tools",
    "UI5_MENU_INSERT_SNIPPET": "Insert snippet",
    "UI5_MENU_OPEN_TEMPL_DIR": "Open snippets folder",
    "UI5_MENU_API_REFERENCE": "API reference",
    "UI5_MENU_ODATA_GEN": "OData mock data generation",
    "OPEN_TEMPL_DIR_ERROR": `${prefix} Error displaying templates folder`,
    "MOCK_DIALOG_TITLE": "Finished",
    "MOCK_DIALOG_DONE": "OData mock files generated.",
    "API_LOADED_INFO": `${prefix} UI5 API index loaded successfully from`,
    "LIBRARY_LOADED_INFO": `${prefix} Library loaded `,
    "URL_GET_ERROR": `${prefix} Could not reach`,
    "URL_XML_GET_ERROR": `${prefix} Could not fetch XML schema (not always error - some libs don't have .xsd)`,
    "XML_SCHEMA_READY": `${prefix} XML schema prepared:`,
    "UI5_OBJECTS_LOAD_ERROR": `${prefix} UI5 API documentation could not be loaded (probabaly connection error has occured). Please reload Brackets.`,
    "METADATA_ERROR": `${prefix} Invalid metadata XML! Reason:`,
    "TOOLBAR_BUTTON": "Toggle UI5 docs panel",
    "DOCS_PANEL_TITLE": "UI5 API reference",
    "SEARCH_PLACEHOLDER": "Type to search",
    "UI5_OBJECTS_DIALOG_TITLE": "UI5 objects",
    "NOT_FOUND": "Not found",
    "FOUND": "Found",
    "NARROW_SEARCH": "Please narrow your search",
    "HITLIST_TITLE": "Did you mean:",
    "LOADING": "Loading...",
    "INSERT_DEFINE": "Insert (define)",
    "METHODS": "Methods",
    "EVENTS": "Events",
    "EXTENDS": "Extends",
    "CONSTRUCTOR": "Constructor",
    "PROPERTIES": "Properties",
    "CLOSE": "Close",
    "OPEN_DOC_PAGE": "Open object's API documentation page",
    "DEPRECATED": "Deprecated!",
    "INSERT_DEFINE_DESC": "Insert object to the existing define statement",
    "INSERT_PATH_DESC": "Insert object's path to the current position.",
    "INSERT": "Insert",
    "INSERT_REPLACE_DESC": "Insert object's path to the current position. '.' will be replaced with /.",
    "FULL_DOC": "Full documentation",
    "SHOW_DESC": "Show descriptions",
    "METHOD": "method",
    "PROPERTY": "property",
    "ERROR": "Error",
    "PREFIX": prefix,
    "INCORRECT_API_VERSION_STRING": `${prefix} UI5 library URL has an incorrect syntax`,
    "ODATA_SERVICE_NOT_LOADED": "The service metadata could not be loaded. Please check the console for errors.",
    "AGGREGATIONS": "Aggregations",
    "MANIFEST_FILE_NOT_FOUND": `${prefix} No manifest.json has been found`,
    "MODEL_DEFINITION_NOT_FOUND": "model definition has not been found in manifest.json",
    "MODEL_READ_ERROR": `${prefix} Model read error`,
    "COMPONENT_ID_NOT_FOUND": `${prefix} Component Id not found in the manifest file`,
    "FILE_NOT_FOUND": `${prefix} File not found`,
    "MOCK_CONFIG_ERROR": "Mock config error - check Brackets console for logs",
    "MULTIPLE_FUNCTIONS_FOUND": `${prefix} Multiple functions found with the name `
});
