language: node_js
node_js: node
notifications:
  email: false
branches:
  only:
  - master
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: LV6XtSqt3FXgaPLTmgoX+xc8rq9wUPrbmOL3QAt+Fim81bbms94SWAbtJ8o9EUVQ+mrzBxYUkr/SM7DmfiOkAZJy4vJsumueREXvm4cy+CsYnNVaUvzPhzE3s2urP3KWfHW9V2lGN/MxvRzd062zBrxPLIvQJFPCCTW6YJgsW97AvV7Mppt2Heor7ATMEn5lEtHwlQbXxNTPNvw55GUJgL5TIKXAlNIY6M3TTh892VPi9z5bfgLb6ou3+argezpY3Po8CfuDAEG4P/vWjWFJaTFx/wn2Z+c7moZDKUCKSxayZ0s7XDOhG1HlFAPks3QCFBideCO1xsnPyWOmoZtTm/8YM4ImcwNyjKNdjHph4XiqpPOGwBx/YVcCLYY5NcityZSqc+FoHAIzsJU384uqRULH/wcwXQciqlLlBWeI7/RxGHwt5pCfiD/hU52JLnPNfIRDa25MYBSCxxlnBYptpAFEWozdPT1U5MBwoJLTx8wTh4ihy1BYowDzAS2n9rza8MfytzpTBMI4KrFOcjGUXfBDmm+oszMEMv9eAEpoPH+tuMW9wDm8bz260ErljDXnIocs/UVtylkagdCV4LU4hflyil0V6efn3j1KQwGRI30uSrGlfvl0PyOfoGjaGLBMz6TAPEeej4ziFZQq3RPwiAsn9gaFqNoc4FIVg+gokfQ=
  file: dist/wozjac.ui5.zip
  on:
    repo: wozjac/brackets-ui5
branch: master
